// Helixert — World Definitions

export const worlds = [
  {
    num: 0,
    name: "First Steps",
    description: "Basic Movement",
    icon: "👣",
    color: "#4d96ff",
    commands: ["h", "j", "k", "l", "g"],
  },
  {
    num: 1,
    name: "Navigation",
    description: "Advanced Movement",
    icon: "🧭",
    color: "#4d96ff",
    commands: ["w", "b", "e", "0", "g", "G"],
  },
  {
    num: 2,
    name: "The Stock Room",
    description: "Select & Delete (Noun-Verb)",
    icon: "📦",
    color: "#4d96ff",
    commands: ["x", "d", "u"],
  },
  {
    num: 3,
    name: "The Flavour Shelf",
    description: "Replace & Swap",
    icon: "🔄",
    color: "#4d96ff",
    commands: ["r", "x", "p"],
  },
  {
    num: 4,
    name: "The Express Lane",
    description: "Find & Till",
    icon: "🎯",
    color: "#4d96ff",
    commands: ["f", "F", "t", "T", ";", ","],
  },
  {
    num: 5,
    name: "The Order Book",
    description: "Insert Mode",
    icon: "✏️",
    color: "#4d96ff",
    commands: ["i", "a", "A", "I", "o", "O"],
  },
  {
    num: 6,
    name: "The Modes Tour",
    description: "Select Mode",
    icon: "🎨",
    color: "#4d96ff",
    commands: ["v", "d", "y", "c", "p"],
  },
  {
    num: 7,
    name: "Spot Check",
    description: "Search",
    icon: "🔍",
    color: "#4d96ff",
    commands: ["/", "?", "n", "N"],
  },
  {
    num: 8,
    name: "The Back Office",
    description: "Advanced Techniques",
    icon: "⚡",
    color: "#4d96ff",
    commands: [".", "u", "U", "%"],
  },
];
