// Helixert — World Definitions

export const worlds = [
    {
        num: 0,
        name: 'First Steps',
        description: 'Basic Movement',
        icon: '的脚步',
        color: '#4ecdc4',
        commands: ['h', 'j', 'k', 'l'],
    },
    {
        num: 1,
        name: 'Navigation',
        description: 'Advanced Movement',
        icon: '🧭',
        color: '#f7a41d',
        commands: ['w', 'b', 'e', '0', 'g', 'G'],
    },
    {
        num: 2,
        name: 'The Stock Room',
        description: 'Select & Delete (Noun-Verb)',
        icon: '📦',
        color: '#ff6b6b',
        commands: ['x', 'd', 'u'],
    },
    {
        num: 3,
        name: 'The Flavour Shelf',
        description: 'Replace & Swap',
        icon: '🔄',
        color: '#ffd93d',
        commands: ['r', 'x', 'p'],
    },
    {
        num: 4,
        name: 'The Express Lane',
        description: 'Find & Till',
        icon: '🎯',
        color: '#6bcb77',
        commands: ['f', 'F', 't', 'T', ';', ','],
    },
    {
        num: 5,
        name: 'The Order Book',
        description: 'Insert Mode',
        icon: '✏️',
        color: '#4d96ff',
        commands: ['i', 'a', 'A', 'I', 'o', 'O'],
    },
    {
        num: 6,
        name: 'The Modes Tour',
        description: 'Select Mode',
        icon: '🎨',
        color: '#9b5de5',
        commands: ['v', 'd', 'y', 'c', 'p'],
    },
    {
        num: 7,
        name: 'Spot Check',
        description: 'Search',
        icon: '🔍',
        color: '#ff85a1',
        commands: ['/', '?', 'n', 'N'],
    },
    {
        num: 8,
        name: 'The Back Office',
        description: 'Advanced Techniques',
        icon: '⚡',
        color: '#00cec9',
        commands: ['.', 'u', 'U', '%'],
    },
];
